function map = seabedInitialization_2d_V2(map)
    % Plot the profile
    plot(map.k, map.profile, 'b');
    xlabel('Distance');
    ylabel('Height');
    title('2d Profile Generated by Sinusoids with Random Amplitudes and Phases');
    grid on;
    % Set x-axis and y-axis limits to 100
    xlim([0, map.dim]);
    ylim([floor(min(map.profile))-map.dim/2, map.dim/2]); 

    % Plot shapes using anchors_x array
    hold on;
    plot(map.anchors_x(1), 0, 'Xr', 'Color', [0.7, 0.7, 0.7], 'MarkerSize', 10); %leader's first position known
    plot(map.anchors_x(1), map.anchors_y(1), 'o', 'MarkerFaceColor', 'g', 'MarkerSize', 10);
    for i = 2:length(map.anchors_x)
        % Generate random color
        color = [min(1,0.01*map.anchors_x(i)),max(0,1-0.01*map.anchors_x(i)),max(1-0.01*map.anchors_x(i))];
        % Plot anchors
        plot(map.anchors_x(i), map.anchors_y(i), 'o', 'MarkerFaceColor', color, 'MarkerSize', 10);
        plot(map.anchors_x(i), (map.anchors_y(i)+map.anchor_offset), 'Xr', 'Color', [0.7, 0.7, 0.7], 'MarkerSize', 10);
    end
end