function [t, profile, anchors_y] = seabedInitialization_2d(anchors_x,amp,phase,num_sin,m_dim)
    % Define the time range
    t = 0:0.1:m_dim; % Time values from 0 to 100 with a step of 0.1

    % Define parameters for the sinusoids
   
    freq = linspace(0.005, 0.1, num_sin)*0.6; % Frequencies of the sinusoids
   
    % Initialize the hill profile
    profile = zeros(size(t));

    % Generate the hill profile by summing sinusoids
    for i = 1:num_sin
        profile = profile + amp(i) * sin(2*pi*freq(i)*t + phase(i));
    end

    % Plot the profile
    plot(t, profile, 'b');
    xlabel('Distance');
    ylabel('Height');
    title('Profile Generated by Sinusoids with Random Amplitudes and Phases');
    grid on;
    % Set x-axis and y-axis limits to 100
    xlim([0, m_dim]);
    ylim([floor(min(profile))-m_dim/2, m_dim/2]); 
    %xticks(0:10:100);
    %yticks(floor(min(profile)):10:100);  
    %axis equal;

    anchors_y = zeros(length(anchors_x));
    % Plot shapes using anchors_x array
    hold on;
    for i = 1:length(anchors_x)
        % Generate random color
        color = [min(1,0.01*anchors_x(i)),max(0,1-0.01*anchors_x(i)),max(1-0.01*anchors_x(i))];
        % Plot anchors
        plot(anchors_x(i), interp1(t, profile, anchors_x(i)), 'o', 'MarkerFaceColor', color, 'MarkerSize', 10);
        % anchors_y
        anchors_y(i) = interp1(t, profile, anchors_x(i);
    end
end
